### ISSUE TITLE
Default-true boolean values are not settable to false

### ISSUE THREAD

**Issue by JoelOtter** [dgkanatsios/playfabsdk-go#1]
Hi there,

I've noticed that some boolean values, which on PlayFab's side are default-true, cannot be set to false using this SDK. This is because these JSON values are marked as `omitempty`.

Here's an [executable example](https://play.golang.org/p/sQn0nhq7SVs) so you can see what I mean.

It would be useful if default-true boolean values could have the `omitempty` dropped in generation.

Thanks!

**Comment by dgkanatsios** [comment]
This should be fixed by the latest commit, apologies for the ultra-slow turnaround! Closing, let me know if the problem persists
